### ISSUE TITLE
I am so confused as to how to run this.

### ISSUE THREAD

**Issue by Gabocota** [rawandahmad698/Dalle-Discord#10]
I tried windows cmd and pip and python 3.10.5 : didn't work.
I tried linux ubuntu latest version with the correct python and pip and packages : 
![image](https://user-images.githubusercontent.com/88735758/187828345-f1833300-f936-4f00-9b61-70f33c30ff14.png)

It just does not work.
Can someone explain how am i supposed to use this?

**Comment by comicsansgreenki** [comment]
It seems to be an issue in the repo's code iteself. I received the same TypeError trying to run it on an Ubuntu 22.04 server.

**Comment by rawandahmad698** [comment]
Hey, discord has enforced the messaging intent, thus this error, It’s a one line code fix and i’ll update it soon

**Comment by comicsansgreenki** [comment]
Ohhh I see now. This appears to be an issue that developed from Discord's new ToS and Bot Intent requirements, hence it erroring out from missing an 'intents' argument.

**Comment by comicsansgreenki** [comment]
oop, my bad. same-timestamp comment >v<

**Comment by comicsansgreenki** [comment]
@Gabocota Bug patched. Try cloning and running the bot now.

**Comment by Gabocota** [comment]
dalle-discord-master-dalle-discord-1 | Traceback (most recent call last):
dalle-discord-master-dalle-discord-1 |   File "/app/bot.py", line 214, in <module>
dalle-discord-master-dalle-discord-1 |     bot.loop.create_task(background_task())
dalle-discord-master-dalle-discord-1 |   File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 108, in __getattr__
dalle-discord-master-dalle-discord-1 |     raise AttributeError(msg)
dalle-discord-master-dalle-discord-1 | AttributeError: loop attribute cannot be accessed in non-async contexts. Consider using either an asynchronous main function and passing it to asyncio.run or using asynchronous initialisation hooks such as Client.setup_hook

**Comment by comicsansgreenki** [comment]
hmm. I suppose it's time for a new issue.
