### ISSUE TITLE
discord.py borked an asyncio function

### ISSUE THREAD

**Issue by comicsansgreenki** [rawandahmad698/Dalle-Discord#15]
in #10, @Gabocota said:

> dalle-discord-master-dalle-discord-1 | Traceback (most recent call last):
dalle-discord-master-dalle-discord-1 | File "/app/bot.py", line 214, in
dalle-discord-master-dalle-discord-1 | bot.loop.create_task(background_task())
dalle-discord-master-dalle-discord-1 | File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 108, in getattr
dalle-discord-master-dalle-discord-1 | raise AttributeError(msg)
dalle-discord-master-dalle-discord-1 | AttributeError: loop attribute cannot be accessed in non-async contexts. Consider using either an asynchronous main function and passing it to asyncio.run or using asynchronous initialisation hooks such as Client.setup_hook

Based on slight research, I think the `master` version of `discord.py` may have broken some things in `asyncio`.

**Comment by rawandahmad698** [comment]
As a workaround, remove the background task function (since it's empty) and delete the line where it's initially initialized before bot.run;) 

There are other ways to run a background task, It's not asyncio related (but discords event loop)

**Comment by comicsansgreenki** [comment]
@Gabocota how bout now?

**Comment by Gabocota** [comment]
Fixed! Thanks
