### ISSUE TITLE
Public bot

### ISSUE THREAD

**Issue by mezotv** [rawandahmad698/Dalle-Discord#5]
Why dont you guys make this a public bot and host it for everyone. I can see alot of servers using it

**Comment by rawandahmad698** [comment]
This is a great Idea, unfortunately I don't have enough time. would love to see do it though

**Comment by comicsansgreenki** [comment]
My copy of the bot has run into Cloudflare ratelimiting problems with someone requesting the same query about 3 times per second.

I'm a little worried that 'alot of servers' may hit that limit somewhat and make the bot less...well...usable, unless shards on multiple IPs are implemented. Either that, or running the Dall-E Mini model locally.

**Comment by mezotv** [comment]
Yea i didnt thought of that makes sense tho

**Comment by rawandahmad698** [comment]
Try proxies, or implement a cloudflare scrapper, there are many on github. Proxies should be used on all sorts of scraping, seeing that this is scraping too; I encourage the use of proxies at all times

**Comment by mezotv** [comment]
Proxys make sense yea. Maybe we will see a dall e mini bot public on discord one day
